---
- name: APT. Update repository cache
  apt: 
    update_cache: yes
  tags:
    - done

- name: Patroni. Install packages
  apt:
    name: "{{ apt_patroni_packages }}"
    state: latest
  tags:
    - done

- name: Postgresql. Install and setup
#  block:
#  - template: 
#      src: pg_hba.conf 
#      dest: /etc/postgresql/12/main/pg_hba.conf 
#      owner: postgres 
#      mode: 0600
  service:
      name: postgresql
      state: restarted
      enabled: yes
  tags:
    - done

- name: Pip. Upgrade
  shell: pip install --upgrade pip

  tags: pip

- name: Pip. install psycopg2-binary
  shell: pip install psycopg2>=2.5.4

  tags:
    - pip

#  Pip. install patroni
- name: Pip. install patroni
  shell: pip3 install patroni python-etcd

  tags:
    - pip

- name: Copy configuration files for patroni on {{ansible_hostname}}
  template:
    src: patroni.yml.j2
    dest: "/etc/patroni.yml"

  tags:
    - pyml  

### Install haproxy

- name: Apt. Install haproxy
  apt:
    name: haproxy
    state: latest
   
  tags:
     - haproxy

- name: Copy configuration files for haproxy
  template:
    src: haproxy.cfg.j2
    dest: "/etc/haproxy/haproxy.cfg"

  tags:
    - ccf

- name: Restart haproxy
  service:
      name: haproxy
      state: restarted
      enabled: yes
  tags:
    - cfg_haproxy

