---
servers:
  hosts:
    debian_virt:

all_hosts:
  children:
    ec_htp:
      vars:
        full_name: "Patroni servers"
      hosts:
        debian_virt:
#          ansible_user: vagrant
          ansible_connection: local
